[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 11.5

[font.bold]
family = "CommitMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "CommitMono Nerd Font"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[terminal]

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
args = ["--distribution", "Ubuntu", "--cd", "/home/derekbiega/"]
program = "wsl.exe"

[window]
decorations = "full"
opacity = 0.85
startup_mode = "Windowed"

[window.padding]
x = 6
y = 6

[selection]
save_to_clipboard = true

[mouse]
bindings = [
{ mouse = "Right", action = "Paste" },
]
